import { Footer, Navbar } from "@/components/Comp";
import { ClerkProvider } from "@clerk/nextjs/app-beta";
import "./globals.css";




export const metadata = {
  title: "Dine Market",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ClerkProvider>
          <Navbar />
          {children}
          <Footer />
        </ClerkProvider>
      </body>
    </html>
  );
}
